language: generic
sudo: required
services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t felipegutierrez/explore-docker/frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true felipegutierrez/explore-docker/frontend npm run test -- --coverage
