language: generic
sudo: required
services:
  - docker
env:
  - CHANGE_MINIKUBE_NONE_USER=true
  global:
    - SHA=$(git rev-parse HEAD)
branches:
  only:
  - master

before_install:
  - sudo apt-get install -y conntrack
  - docker build -t felipeogutierrez/explore-docker/frontend -f ./frontend/Dockerfile.dev ./frontend
  - docker build -t felipeogutierrez/explore-docker/complex -f ./complex/client/Dockerfile.dev ./complex/client
addons:
  apt:
    update: true

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.18.3
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
  - docker run -e CI=true felipeogutierrez/explore-docker/frontend npm run test -- --coverage
  - docker run -e CI=true felipeogutierrez/explore-docker/complex npm test

after_success:
  - docker build -t felipeogutierrez/explore-docker-complex-client:latest -t felipeogutierrez/explore-docker-complex-client:$SHA ./complex/client
  - docker build -t felipeogutierrez/explore-docker-complex-nginx:latest -t felipeogutierrez/explore-docker-complex-nginx:$SHA ./complex/nginx
  - docker build -t felipeogutierrez/explore-docker-complex-server:latest -t felipeogutierrez/explore-docker-complex-server:$SHA ./complex/server
  - docker build -t felipeogutierrez/explore-docker-complex-worker:latest -t felipeogutierrez/explore-docker-complex-worker:$SHA ./complex/worker
  # Log in to the docker CLI. Log in to docker in a single command line
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the images and push them to docker.hub
  - docker push felipeogutierrez/explore-docker-complex-client:latest
  - docker push felipeogutierrez/explore-docker-complex-nginx:latest
  - docker push felipeogutierrez/explore-docker-complex-server:latest
  - docker push felipeogutierrez/explore-docker-complex-worker:latest
  - docker push felipeogutierrez/explore-docker-complex-client:$SHA
  - docker push felipeogutierrez/explore-docker-complex-nginx:$SHA
  - docker push felipeogutierrez/explore-docker-complex-server:$SHA
  - docker push felipeogutierrez/explore-docker-complex-worker:$SHA
  - kubectl apply -f complex-kubernetes/k8s
  - kubectl set image deployments/client-deployment client=felipeogutierrez/explore-docker-complex-client:$SHA
  - kubectl set image deployments/server-deployment server=felipeogutierrez/explore-docker-complex-server:$SHA
  - kubectl set image deployments/worker-deployment worker=felipeogutierrez/explore-docker-complex-worker:$SHA